// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgHraTm4N3z9kOo0D_0j8n_c8V42ua6wo',
    appId: '1:547152242825:web:c4de385428801cea527e58',
    messagingSenderId: '547152242825',
    projectId: 'ebay-demo-2ec23',
    authDomain: 'ebay-demo-2ec23.firebaseapp.com',
    storageBucket: 'ebay-demo-2ec23.appspot.com',
    measurementId: 'G-P6HW4J8W9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp0-F2bJjEs2UUtsnXpaf-szDzHqZpBnQ',
    appId: '1:547152242825:android:4500106fb46e3387527e58',
    messagingSenderId: '547152242825',
    projectId: 'ebay-demo-2ec23',
    storageBucket: 'ebay-demo-2ec23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHxxb5bDaqY9FcK61MgPwta7rbNgMhG3g',
    appId: '1:547152242825:ios:03db5969e13e0569527e58',
    messagingSenderId: '547152242825',
    projectId: 'ebay-demo-2ec23',
    storageBucket: 'ebay-demo-2ec23.appspot.com',
    androidClientId: '547152242825-81m5cboipnc7sudf7vv65j7of2168j0a.apps.googleusercontent.com',
    iosClientId: '547152242825-5pgam7mnjtr5gnufa70aelguvlhbubmb.apps.googleusercontent.com',
    iosBundleId: 'exit',
  );
}
